### ISSUE TITLE
Include a reference table of supported metrics

### ISSUE THREAD

**Issue by josevalim** [beam-telemetry/telemetry_metrics_prometheus#20]
I believe all reporters should include a table with the name of the Telemetry.Metric and what is their equivalent on the report terminology. Something like this:

Telemetry Metric | XYZ Metric
------------ | -------------
counter | ...
last_value | ...
sum | ...
summary | ...
histogram | ...

If a metric is not supported, that's a good place to document it too.

WDYT?

**Comment by bryannaegele** [comment]
@josevalim yeah, I do have that in the module docs in https://hexdocs.pm/telemetry_metrics_prometheus_core/TelemetryMetricsPrometheus.Core.html#module-telemetry-metrics-to-prometheus-equivalents. It should probably be added to the overview doc. 

Were you thinking to add it to the README, as well?

**Comment by josevalim** [comment]
@bryannaegele ah, so that's fine. Apologies for missing it!
