### ISSUE TITLE
Unable to start multiple instances in a single VM

### ISSUE THREAD

**Issue by jeffgrunewald** [beam-telemetry/telemetry_metrics_prometheus#26]
From a Plug.Cowboy perspective, should it be possible to run multiple instances of the Telemetry.Metrics.Prometheus in the same VM as long as they're configured to use different ports?

Our umbrella app normally runs with individual components in separate containers in production but all together in a single Erlang VM for end-to-end testing and I'm getting `failed to connect: eaddrinuse` error messages when more than one instance of the exporter plug web server is turned on at once. Each component runs an instance of the exporter via a module that pulls in the exporter via a using macro and runs its own instance under a different registered name. Each using macro feeds the different exporter instances a different port on startup but something is still registering a conflict.

Am I missing something about what Plug/Cowboy considers a requirement for a unique address?

**Comment by bryannaegele** [comment]
@jeffgrunewald can you post the configuration you're using? There must be a conflict somewhere in your setup. If you set the port differently for each instance, it will work.

Are you getting this running under `mix test` by chance?

**Comment by jeffgrunewald** [comment]
That's my hope; I figure I can always strip it down to the prometheus telemetry metrics core and macro out the webserver myself if need be but I'd rather avoid that if possible.

I get the failure when I try to start the app with `iex -S mix` from the `platform_runner` app that starts all the services in the same vm.

The relevant additions to the project are all in this draft PR: https://github.com/inhindsight/hindsight/pull/200. Of note:
- The `metrics_reporter` library within the umbrella provides the using macro wrapper around the exporter that allows the app implementing the exporter to customize the registered process names and the port.
- The `service_acquire` and `service_broadcast` applications in the umbrella both implement the metrics_reporter behaviour; acquire explicitly sets the port to 9568 and broadcast sets it to 9569. 

When I start an individual app like `service_acquire` or `service_broadcast` from their own subdirectory with `iex -S mix` they start individually with no problem and I can verify that the `getter(:port, default: 9568)` directive is being applied so each app is starting the exporter on the port I'm expecting.

The `getter` macros at the beginning of each service is just some magic to pull the config from app_env at boot but since I'm not setting that at the moment, it's falling back to the default value in each app (9568 and 9569 respectively). That way I can set the ports to be different in each service during the all-in-one e2e test but let each one just use the default when they're running in their own isolated containers in production.

**Comment by jeffgrunewald** [comment]
Small side note that I'm currently running off a fork of the project in my own github since the first issue I ran into was a `already_started` error from the web server supervisor since it's just registering itself with the module name. Was planning to open a PR if I'm able to get around the address in use error.

**Comment by bryannaegele** [comment]
So it fails to finish loading on `iex -S mix` at the umbrella level? Or that loads successfully and then fails when you run some other code.

**Comment by jeffgrunewald** [comment]
At the umbrella level.

**Comment by jeffgrunewald** [comment]
But to make sure the various phoenix apps and similar components don't have conflicts you'd want to actually run `MIX_ENV=integration iex -S mix` from within the platform_runner sub application since that apps whole purpose is to orchestrate all the different components in this specific scenario of sharing a VM and overriding default ports via each components own `integration` mix environment.

**Comment by bryannaegele** [comment]
So my suspicion is that macro + umbrella is not setting the values you're wanting or there is another instance of the application already running. I suggest adding some debug logs to print the port out when it runs and see where the conflict is occurring.

I can say this is not an issue with this library or cowboy. If the port is in use, that's at the system OS level. In our setup at WM, we have this working in every project. We have to set a different port when running tests in a running docker container, so the instance grabs the config at runtime and we set it differently for the test env.

I'm happy to re-open this if you can provide a failing test in this library.

**Comment by jeffgrunewald** [comment]
Thanks for looking. From watching an `lsof` and dropping inspects of the config options into my fork of the library i can guarantee they are not using the same ports.

Under the hood, they are both trying to create a plug module called `TelemetryMetricsPrometheus.Router.HTTP` and then each one is telling that module to use a different port. I suspect that's a problem when it's all happening in the same instance of the BEAM. It's a weird and arguably artificial scenario we're in so I can understand why no one has found it to be a problem before. We probably shouldn't be doing it 😁 

My takeaway is that I should be expanding my macros to create a unique router/supervisor wrapper for each service and pulling in the TelemetryMetricsPrometheus.Core library instead.

**Comment by bryannaegele** [comment]
@jeffgrunewald I found the issue and it's a problem that @josevalim noted in elixir-plug/plug_cowboy/issues/20#issuecomment-571990525.

As a workaround, you can do:

```
TelemetryMetricsPrometheus.child_spec(name: :prom_server_1, metrics: [], port: 9987, plug_cowboy_opts: [ref: make_ref()]))
TelemetryMetricsPrometheus.child_spec(name: :prom_server_2, metrics: [], port: 9988, plug_cowboy_opts: [ref: make_ref()]))
```

I verified both the error you saw and this workaround locally.

**Comment by jeffgrunewald** [comment]
Brilliant! Also verified; thanks very much!
