### ISSUE TITLE
Incompatible with telemetry_metrics 0.5.0

### ISSUE THREAD

**Issue by isaacsanders** [beam-telemetry/telemetry_metrics_prometheus#28]
After the changes to telemetry_metrics in 0.5.0, this project needs to be updated.

**Comment by bryannaegele** [comment]
0.5.0 was released this morning and we do not coordinate updating every library in the ecosystem at the same time. We're aware of the breaking changes and encourage users not to update `telemetry_metrics` in your project until other libraries you're using are updated.

**Comment by bryannaegele** [comment]
`TelemetryMetricsPrometheus.Core` v0.4.0 has been released with support for `Telemetry.Metrics` v0.5.0
