### ISSUE TITLE
Divergence from Prometheus Python Client

### ISSUE THREAD

**Issue by isaacsanders** [beam-telemetry/telemetry_metrics_prometheus#39]
Hey all, I was looking into some work between elixir and python, and I saw that this package and the prometheus python client might be diverging in the implementations. This file/line in particular are an example I found: https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics.py#L610

**Comment by bryannaegele** [comment]
Can you elaborate on exactly what difference you think there is? I can't tell from just looking at that line.

**Comment by isaacsanders** [comment]
There’s an extra metric `<histogram prefix>_created`

**Comment by bryannaegele** [comment]
It's something they made up. It's not in the spec.

https://prometheus.io/docs/instrumenting/writing_clientlibs/#histogram
