### ISSUE TITLE
Ability to register multiple metrics with same name

### ISSUE THREAD

**Issue by ananthakumaran** [beam-telemetry/telemetry_metrics_prometheus#40]
I have a use case where I need to capture different telemetry events as a single prometheus metric. Part of the key in the telemetry event would be converted to prometheus label. I expected the below approach to work, but the second one overwrites the first one because we use the metric name as the id in the attach call. Any idea how I can handle this case?

```
[
  last_value([:job, :pending, :total],
    event_name: [:queue, :foo, :pending],
    tags: [:queue],
    tag_values: fn _ -> %{queue: :foo} end
  ),
  last_value([:job, :pending, :total],
    event_name: [:queue, :bar, :pending],
    tags: [:queue],
    tag_values: fn _ -> %{queue: :bar} end
  )
]
```

**Comment by bryannaegele** [comment]
Hey @ananthakumaran. Whatever is emitting those events is not following standard practices on event naming. The given example has a couple telemetry anti-patterns.  The `bar` and `foo` in your examples should be a part of the metadata of the event and not part of the event name. Same goes for the `pending` part.

In the given example, the event should be something like `[:<<app_name>>, :queue, :length]` with metadata of

```elixir
%{
  queue: :foo,
  status: :pending
}
```

Fixing the underlying issue should resolve your predicament.

**Comment by ananthakumaran** [comment]
I thought I could somehow handle it on the receiver side :). Agree with your point, it should be fixed on the emitter side.

**Comment by ananthakumaran** [comment]
I ran into the same problem again today with phoenix. I need to capture the duration of all the requests including 500 errors as well, and since phoenix publishes it as two events, there is no way to capture it as a single prometheus metric

```elixir
[:phoenix, :router_dispatch, :stop]
[:phoenix, :router_dispatch, :exception]
```

**Comment by bryannaegele** [comment]
You can combine the two metrics with promql in whatever tooling you are using.
