### ISSUE TITLE
Change the handler_id to use event_name instead of metric_name

### ISSUE THREAD

**Issue by jhonndabi** [beam-telemetry/telemetry_metrics_prometheus#43]
Hi @bryannaegele,

We have the following scenario, we want to publish metrics from Ecto, with the same metric_name even though the event_name is different.

```elixir
[
 %{metric_name: [:ecto, :query], event_name: [:my_app, :repo, :query]},
 %{metric_name: [:ecto, :query], event_name: [:my_app, :another_repo, :query]},
 %{metric_name: [:ecto, :query], event_name: [:another_app, :repo, :query]}
]
```

That way we can build only one dashboard with the same query for each panel at Grafana with a selector for each repo, retrieving the repo from labels.

And I think we can achieve that, changing the event handler_id to use event_name instead of metric_name. What do you think?

**Comment by bryannaegele** [comment]
You can't have more than one metric of the same name in Prometheus, so this isn't possible. What you're looking for is to just use the same name but have attributes with the values you want to key on. Then just update your Grafana dashboard to use that attribute as a selector.
