### ISSUE TITLE
Reset after scrape

### ISSUE THREAD

**Issue by isaacsanders** [beam-telemetry/telemetry_metrics_prometheus#6]
Hey Bryan, I am working on implementing more observability in my team's systems, and I stumbled across your project.

As I understand it, there is no documented way to reset metrics.

Would you accept a PR for a configuration option to reset on scrape?

**Comment by bryannaegele** [comment]
Hey, @isaacsanders! Sorry I missed this somehow. 

Could you tell me what you're trying to accomplish? Prometheus metrics are not intended to be reset except in the case of a server restart.

**Comment by isaacsanders** [comment]
I don't know much about Prometheus, so I hope you'll pardon my ignorance. If the reset is only on restart, then there isn't really an action item here.
